
@host = http://localhost:8080
@admin_token = {{login_admin.response.body.token}}
@user_token = {{login_user.response.body.token}}

#Registro de usuario administrador
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "email": "administrador@regata.com",
  "roles": ["admin"]
}

#Registro de usuario jugador
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "jugador",
  "password": "jugador123",
  "email": "jugador@regata.com",
  "roles": ["user"]
}

#Login como administrador
# @name login_admin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

#Login como jugador
# @name login_user
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "jugador",
  "password": "jugador123"
}


#Listar todos los barcos (solo ADMIN)
GET {{host}}/api/barco/list
Authorization: Bearer {{admin_token}}

#Obtener barco por ID (ADMIN)
GET {{host}}/api/barco/1
Authorization: Bearer {{admin_token}}

#Intentar obtener barco con ID inexistente
GET {{host}}/api/barco/555
Authorization: Bearer {{admin_token}}

#Listar barcos por jugadorId (ADMIN)
GET {{host}}/api/barco/list/2
Authorization: Bearer {{admin_token}}

#Crear nuevo barco (ADMIN)
POST {{host}}/api/barco
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "velocidad": 2.5,
  "posicionId": 1,
  "modeloId": 2,
  "jugadorId": 3,
  "tableroId": 1
}


#Actualizar barco existente (ADMIN)
PUT {{host}}/api/barco
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "id": 1,
  "velocidad": 3.0,
  "posicionId": 1,
  "modeloId": 2,
  "jugadorId": 3,
  "tableroId": 1
}

#Eliminar barco (ADMIN)
DELETE {{host}}/api/barco/1
Authorization: Bearer {{admin_token}}

#Buscar barco por texto (ADMIN)
GET {{host}}/api/barco/search?searchText=Velero
Authorization: Bearer {{admin_token}}




#Jugador intentando listar barcos (debe fallar)
GET {{host}}/api/barco/list
Authorization: Bearer {{user_token}}

# Sin token (debe fallar)
GET {{host}}/api/barco/list

#Jugador selecciona barco (permitido)
POST {{host}}/api/auth/select-barco?userId=2&barcoId=3
Authorization: Bearer {{user_token}}

# Listar barcos disponibles para jugador
GET {{host}}/api/auth/available-barcos?userId=2
Authorization: Bearer {{user_token}}


